defaults: distillation_icpc_qwen3_0_6b_from_1_7b.yaml

distillation:
  teacher_update_mode: fixed
  teacher_update_period: 1

policy:
  model_name: Qwen/Qwen3-14B
  tokenizer:
    name: ${..model_name}
  train_global_batch_size: 32
  generation_batch_size: 32
  logprob_batch_size: 1
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 1
    context_parallel_size: 1
  generation:
    vllm_cfg:
      tensor_parallel_size: 2
      gpu_memory_utilization: 0.6

teacher:
  model_name: ${policy.model_name}
  tokenizer:
    name: ${..model_name}
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 1
    context_parallel_size: 1

checkpointing:
  checkpoint_dir: checkpoints/distillation-icpc-qwen3-14b-selfdistill

logger:
  log_dir: logs/distillation-icpc-qwen3-14b-selfdistill
  wandb:
    name: distillation-icpc-qwen3-14b-selfdistill
